### ISSUE TITLE
Should we support open-source Swift for Linux?

### ISSUE THREAD

**Issue by camelpunch** [camelpunch/RMQClient#14]
Points of interest:

- Does this imply dropping support for Objective-C users, or creating two ports?
- Can we implement in portable Objective-C to maintain easy support for Obj-C iOS projects?
- How much of Foundation do we currently rely upon?

**Comment by nimtiazm** [comment]
It'll be useable across the platforms if we use open source Swift.
Is there any logical argument for the otherwise? No.
Even better, use Swift Package Manager and let the project mature with the open source compiler and package manager.

**Comment by briancroom** [comment]
Hi @nimtiazm, thanks for your interest in the project! I'm not on the development team, but was involved in the discussions when it was decided to use Objective-C for this project, so I can provide some insight.

There are a few things that made Objective-C an attractive choice for the project at this time:
* The team had more familiarity with Objective-C
* The maintenance effort is lower because there are no breaking changes happening to the language
* It doesn't require app developers to ship the Swift standard library with their app if they don't want to
* The library developers don't have to worry about whether a particular language feature is or isn't bridgeable (since one core goal of the project is for it to be usable by Objective-C devs)

Additionally, the cross-platform advantages of Swift wouldn't be available yet anyway, because key dependencies of the project are either unavailable (e.g. CocoaAsyncSocket) or very immature (Foundation) on non-Apple platforms.

Down the road a bit further, when the Swift ABI reaches stability, the stdlib isn't required to be shipped directly by apps anymore, and the Swift Corelibs projects like Foundation and libdispatch are closer to production-readiness, the benefits of using Swift for cross-platform capabilities will be much clearer.

In the meantime, it would be helpful if you could keep a look out for a cross-platform Swift library providing functionality similar to CocoaAsyncSocket which would be a requirement before we could even consider migrating to Swift.

**Comment by camelpunch** [comment]
Closing as I think this answers the question. We'll definitely be looking at this down the road.

**Comment by mackoj** [comment]
It coud be great if you could consider revisiting this decision

**Comment by michaelklishin** [comment]
@mackoj this client won't move to Swift. Nothing but the lack of time prevents us from developing an identical, and even better, client in Swift.

**Comment by adib** [comment]
@briancroom [Vapor Sockets](https://github.com/vapor-community/sockets) seems to be promising. Failing that there's [a number of swift libraries offering sockets and asynchronous handling](https://libraries.io/explore/swift-sockets-libraries).

Having a Swift/Linux client for RabbitMQ would be great for server-side scenarios.

**Comment by michaelklishin** [comment]
An update since this question keeps coming up (e.g. in #165).

This client is implemented in Objective-C and that won't change. A pure Swift might be an option but likely will have to use a different set of I/O dependencies. I don't know when our team would have the cycles to work on that.

This is open source software, though, so you are welcome to contribute a prototype.

**Comment by funcmike** [comment]
Hi,
If anyone is still looking for RabbitMQ client working on Linux I'm making one:  [https://github.com/funcmike/rabbitmq-nio](https://github.com/funcmike/rabbitmq-nio).
It's very early days - any help will be appreciated.

**Comment by helje5** [comment]
Objective-C works just fine on Linux FWIW. Since like forever (e.g. both [OpenGroupware.org](http://www.opengroupware.org) and [ScalableOGo.org](ScalableOGo.org) are server side ObjC examples that run on Linux since about 1999).
[GNUstep-base](https://github.com/gnustep/libs-base) is a pretty great Foundation implementation that should ship w/ most Linux's by default (and there is also libFoundation, which I worked on, but is less complete).
